name: Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Test Suite
        run: |
          go test ./...
